name: Testing with devbox

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install devbox
        uses: jetpack-io/devbox-install-action@v0.8.0

      - name: Run arbitrary commands
        run: devbox init

      - name: kubectl version
        run: devbox run -- kubectl version --client

      - name: python version
        run: python --version
